create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  platform text not null check (char_length(trim(platform)) > 0),
  topic text not null check (char_length(trim(topic)) > 0),
  content text not null check (char_length(trim(content)) > 0),
  consent_to_store boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.forum_posts enable row level security;

create policy "Allow anonymous read access to forum posts"
on public.forum_posts
for select
to anon
using (true);

create policy "Allow anonymous insert with consent"
on public.forum_posts
for insert
to anon
with check (consent_to_store = true);
